---
services:
  - docker
sudo: required
env:
  global:
    - DOCKER_REPOSITORY=storecore/php
    - ECR_REPOSITORY=storecore-php
    - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.gz
    - SAUCE_USERNAME=storecorebot
    -
      secure: 1c+Dq63I4mxbDgxW5a1m+Y/HXe1F50Hr5iytOMEYAxpV/BTAq6/etnpanGHw6rBNh+GiH1KpELzvr21Q/Tz0OJTrXWtCieRXiwWxQFiB3qhoK3GpKPPkpHXBf5rhUqPDjDzDSUTUAFQvSWby3RIuJRykP4rS+MxYl+5WdNIzw2PSjCzYELwgs4BnBZ38kV3W6HVc8xmLRfQ1Hsssj7D6ADMUN+dNNRGdYZfE5YYPZlEyjsXmtJJ928MTQf6GuNKnSRY3lwUlkXAK0UT6R9U7y41FVE3oLqIEASBK5p+cEqYz+hMFKMCtORdfc9W7cYrZLAsn18UAHsdK3DBQ+rH3nX5W/ASuAPlcfE4+qd1MkzQBA3q19uoUJg5xJbrALxr9DmXw3LdsSGJySYqNnSFL45xq5CMulWrLkne2zMlCj1QZCOgXkoIFLHbwRLgoIGkJxRWs8qKKhSIhZdeFAxaIb8GDNCafGxocH3VZ10BfTjw8LVVnQmWNxWTPpuwWKzvYhohmNW0eRo4qExsUBtLUzsYkQJm960qF+9IcyX3aOUXNXrD3o4HYfr5k9O2RtRkVAg0Y3G+Nzs9vJ/Fz1POsvymP5BdqdKLuFOFOx2Dn06UfGklBInBEUsZpzJ3Alo6ycwi/VfMZKH/L0iUD5tLiwJAiL3nHlbB8F/rl18mMtfY=
    -
      secure: JnJJSM/Cjwc9LatY14yAuBHBl7rpXgz8jUWV5/68HUYh6JEL6OFI1U0Tiin+KUqSR4s0hgIAa3xudZTBQfkW954R+LPLzeltgAl/xK/AinKSuEmNddb30HwvCsFiuoJUEqtA3aBGDh90yisxB8EAKp934wRDMAQ31U4M7DsmrW0=
    -
      secure: ghtOA+KNZHNVJz37eqUC5air9XrPu7XW524brNJwi9bCNlLY7A4/OmbU+9+MQ8XTRzb4QFdJZjadKUdiQbjEGyGywtV5VY7NahO2NB0u3awy1rpqIGNmiko/ZUJ0YLqvVxtvGMfcXSWYRYsR/ymmbwe8fXYkHw3jsnhjTWh33KM=
    -
      secure: YJv4k5Q02kHdBnamEUemEU26EZk1ki9dJoXhZm1l4MHTLNHf/tBL7CbX6fdLBca8WztQJVY0SJuymvXFd3D1Gj8saFvSpDCM/7G60OqBmTO4nt9O5XPVtbARbfZwPNsZNbUZqq0VcLUHZjEElcNY+gufRzXa/E06YkSMAaxdNsY=
    -
      secure: Eu7YQ9eLVgakRIAxYrXCiqan4Esw93fiu818heOyzuA/wDBJjHS5j3JLRQiF1bdrMLZRdJdix8qQxYSkFbEhkLSHkuBN4Fyibxi0GyKcYi+rUhUIbyx53Vl7Hcc8mBPz/p8Jas66CZSkbSuhd4RV1oyb+FYxcy0eT3oL8tpLaP8=
    -
      secure: Q6jD6jtfudr4mEJ27L10++WkIiQgeet8nInVguD/Q35XuU5IY8zq6tQrr2WW4rLpGExrhjT/dHvWnHN86YtrrSo/mD5YdtjR3XY5XtLDlD/0tS7X4FsyHXqWm7rfWiMTBK/YF+RGv0p/9ZFsV7dlWxUJwohUBfXoYC0RB3BRNjo=
addons:
  jwt:
    secure: Ng/PbtYJJxvbf39Agdymw1z5GhecN/InR5NSDD+jMPLzEoJWHvlLGF+cLKcte5qaqGb/fkBJOvEN1YEH2vzLOd4NY8hTZ8aA3NTAjNK0+CZDLZjqm8v5ubfr0m1wfINYG2K5tj+p86Osr733ysxP5+wUeSop5Q/1BR9BucUn1oM=
cache:
  directories:
    - /home/travis/docker/
before_install:
  - "docker --version"
  - 'if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then echo "ENV GIT_SHA ${TRAVIS_COMMIT::8}" >> Dockerfile; fi'
  - 'if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]] && [[ -f ${DOCKER_CACHE_FILE} ]]; then gunzip -c ${DOCKER_CACHE_FILE} | docker load; fi'
before_script:
  - "env > .env"
install:
  - 'if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT::8} --pull=true .; fi'
language: php
notifications:
  slack:
    secure: gWmuVlLp8Jc7lPdm1ME7CZ9KgIlo+HoD5Dn/BqFN5rgbsDsmk4usEz7f7eknR1WAsijRwC3dMbTPm1KayfnFgtSSYQN3bmihNK6FVMH8DoCAugH4/HsZerSV1PRATPwPv06eGOARbXhzWeJJayhSWIxVfGILfhRF5vjJ7FWZ1cM=
php:
  - "5.6"
script:
  - "phpunit --bootstrap tests/bootstrap.php --testdox tests --coverage-text"
  - 'if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then mkdir -p $(dirname ${DOCKER_CACHE_FILE}) ; docker save $(docker history -q ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT::8} | grep -v "<missing>") | gzip > ${DOCKER_CACHE_FILE}; fi'
after_success:
  - 'if [[ $TRAVIS_PHP_VERSION == "5.6" ]] && [[ $TRAVIS_BRANCH == "develop" ]] && [[ $TRAVIS_PULL_REQUEST == "false" ]]; then sh generate-api.sh; fi'
  - 'if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}; fi'
  - 'if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then docker tag ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT::8} ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT::8}; fi'
  - 'if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then docker tag ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT::8} ${DOCKER_REPOSITORY}:travis-${TRAVIS_BUILD_NUMBER}; fi'
  - 'if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then docker tag ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT::8} ${AWS_ACCOUNT_NUMBER}.dkr.ecr.eu-west-1.amazonaws.com/${ECR_REPOSITORY}:${TRAVIS_COMMIT::8}; fi'
  - 'if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then docker push ${DOCKER_REPOSITORY}; fi'
  - 'if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then pip install --user awscli; fi'
  - 'if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then export PATH=$PATH:$HOME/.local/bin; fi'
  - 'if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then eval $(aws ecr get-login --region eu-west-1); fi'
  - 'if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then docker push ${AWS_ACCOUNT_NUMBER}.dkr.ecr.eu-west-1.amazonaws.com/${ECR_REPOSITORY}:${TRAVIS_COMMIT::8}; fi'
