language: php
php:
- '5.6'
script: phpunit --bootstrap tests/bootstrap.php --testdox tests --coverage-text
notifications:
  slack:
    secure: gWmuVlLp8Jc7lPdm1ME7CZ9KgIlo+HoD5Dn/BqFN5rgbsDsmk4usEz7f7eknR1WAsijRwC3dMbTPm1KayfnFgtSSYQN3bmihNK6FVMH8DoCAugH4/HsZerSV1PRATPwPv06eGOARbXhzWeJJayhSWIxVfGILfhRF5vjJ7FWZ1cM=
env:
  global:
  - SAUCE_USERNAME=storecorebot
  - secure: 1c+Dq63I4mxbDgxW5a1m+Y/HXe1F50Hr5iytOMEYAxpV/BTAq6/etnpanGHw6rBNh+GiH1KpELzvr21Q/Tz0OJTrXWtCieRXiwWxQFiB3qhoK3GpKPPkpHXBf5rhUqPDjDzDSUTUAFQvSWby3RIuJRykP4rS+MxYl+5WdNIzw2PSjCzYELwgs4BnBZ38kV3W6HVc8xmLRfQ1Hsssj7D6ADMUN+dNNRGdYZfE5YYPZlEyjsXmtJJ928MTQf6GuNKnSRY3lwUlkXAK0UT6R9U7y41FVE3oLqIEASBK5p+cEqYz+hMFKMCtORdfc9W7cYrZLAsn18UAHsdK3DBQ+rH3nX5W/ASuAPlcfE4+qd1MkzQBA3q19uoUJg5xJbrALxr9DmXw3LdsSGJySYqNnSFL45xq5CMulWrLkne2zMlCj1QZCOgXkoIFLHbwRLgoIGkJxRWs8qKKhSIhZdeFAxaIb8GDNCafGxocH3VZ10BfTjw8LVVnQmWNxWTPpuwWKzvYhohmNW0eRo4qExsUBtLUzsYkQJm960qF+9IcyX3aOUXNXrD3o4HYfr5k9O2RtRkVAg0Y3G+Nzs9vJ/Fz1POsvymP5BdqdKLuFOFOx2Dn06UfGklBInBEUsZpzJ3Alo6ycwi/VfMZKH/L0iUD5tLiwJAiL3nHlbB8F/rl18mMtfY=
addons:
  jwt:
    secure: Ng/PbtYJJxvbf39Agdymw1z5GhecN/InR5NSDD+jMPLzEoJWHvlLGF+cLKcte5qaqGb/fkBJOvEN1YEH2vzLOd4NY8hTZ8aA3NTAjNK0+CZDLZjqm8v5ubfr0m1wfINYG2K5tj+p86Osr733ysxP5+wUeSop5Q/1BR9BucUn1oM=

after_success:
  - if  [ $TRAVIS_PHP_VERSION = '5.6' ] && [ $TRAVIS_BRANCH = 'develop' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh generate-api.sh; fi
