codecov:
  max_report_age: off
  notify:
    require_ci_to_pass: yes
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
