{
  "manifest_version": <?php echo $manifest_version ?>,
  "name": "<?php echo $name ?>",
  <?php if (!empty($short_name)): ?>
  "short_name": "<?php echo $short_name ?>",
  <?php endif; ?>
  "start_url": "<?php echo $start_url ?>",
  "icons": [
    {
      "src": "/admin/images/StoreCore-icon-64x64.png",
      "sizes": "64x64",
      "type": "image/png"
    },
    {
      "src": "/admin/images/StoreCore-icon-114x114.png",
      "sizes": "114x114",
      "type": "image/png"
    },
    {
      "src": "/admin/images/StoreCore-icon-144x144.png",
      "sizes": "144x144",
      "type": "image/png"
    },
    {
      "src": "/admin/images/StoreCore-icon-152x152.png",
      "sizes": "152x152",
      "type": "image/png"
    },
    {
      "src": "/admin/images/StoreCore-icon-196x196.png",
      "sizes": "196x196",
      "type": "image/png"
    }
  ],
  "background_color": "<?php echo $background_color ?>",
  "theme_color": "<?php echo $theme_color ?>",
  "display": "standalone",
  "orientation": "portrait"
}
