{
  "manifest_version": <?php echo $manifest_version ?>,
  "name": "<?php echo $name ?>",
  <?php if (!empty($short_name)): ?>
  "short_name": "<?php echo $short_name ?>",
  <?php endif; ?>
  "start_url": "<?php echo $start_url ?>",
  "icons": [
    {
      "src": "/images/StoreCore-icon-192x192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "/images/StoreCore-icon-256x256.png",
      "sizes": "256x256",
      "type": "image/png"
    },
    {
      "src": "/images/StoreCore-icon-384x384.png",
      "sizes": "384x384",
      "type": "image/png"
    },
    {
      "src": "/images/StoreCore-icon-512x512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ],
  "background_color": "<?php echo $background_color ?>",
  "theme_color": "<?php echo $theme_color ?>",
  "display": "standalone",
  "orientation": "portrait"
}
