<div class="container">
  <h1><i class="fa fa-sign-in"></i> <?php echo STORECORE_I18N_COMMAND_SIGN_IN ?></h1>
  <form action="/admin/sign-in/" autocomplete="on" method="post" onsubmit="this.style.cursor='wait';document.getElementById('submit').setAttribute('disabled', 'disabled');" target="_top">
    <table>
      <tr>
        <th><label for="username"><?php echo STORECORE_I18N_HEADING_USERNAME ?></label></th>
        <td><input autofocus id="username" name="username" type="text"></td>
      </tr>
      <tr>
        <th><label for="password"><?php echo STORECORE_I18N_HEADING_PASSWORD ?></label></th>
        <td><input autocomplete="off" id="password" name="password" required type="password"></td>
      </tr>
    </table>
    <div>
      <input name="token" type="hidden" value="<?php echo $token ?>">
      <input id="submit" type="submit" value="<?php echo STORECORE_I18N_COMMAND_SIGN_IN ?>">
    </div>
  </form>
</div>