<form action="/admin/settings/users/" autocomplete="on" method="post" target="_top">
  <div class="mdl-card mdl-shadow--4dp">
    <div class="mdl-card__title">
      <h2 class="mdl-card__title-text"><?php echo \StoreCore\I18N\HEADING_USER_ACCOUNT ?></h2>
    </div>
    <div class="mdl-card__supporting-text">
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input autocomplete="email" class="mdl-textfield__input" id="email_address" name="email_address" required type="email" value="<?php echo $email_address ?>">
        <label class="mdl-textfield__label" for="email_address"><?php echo \StoreCore\I18N\HEADING_EMAIL_ADDRESS ?></label>
      </div>
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input autocomplete="given-name" class="mdl-textfield__input" id="username" name="username" type="text" value="<?php echo $username ?>">
        <label class="mdl-textfield__label" for="username"><?php echo \StoreCore\I18N\HEADING_USERNAME ?></label>
      </div>
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input autocomplete="off" class="mdl-textfield__input" id="password" name="password" pattern=".{7,}" required type="password">
        <label class="mdl-textfield__label" for="password"><?php echo \StoreCore\I18N\HEADING_PASSWORD ?></label>
      </div>
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input autocomplete="off" class="mdl-textfield__input" id="confirm_password" name="confirm_password" pattern=".{7,}" required type="password">
        <label class="mdl-textfield__label" for="confirm_password"><?php echo \StoreCore\I18N\HEADING_CONFIRM_PASSWORD ?></label>
      </div>
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input autocomplete="off" class="mdl-textfield__input" id="pin_code" maxlength="6" name="pin_code" pattern="[0-9]{4,6}" required size="6" type="text">
        <label class="mdl-textfield__label" for="pin_code"><?php echo ucfirst(\StoreCore\I18N\NOUN_PIN_CODE); ?></label>
      </div>
    </div>
    <div class="mdl-card__actions mdl-card--border">
      <a class="mdl-button mdl-js-button mdl-js-ripple-effect" href="/admin/settings/users/">
        <?php echo \StoreCore\I18N\COMMAND_CANCEL; ?>
      </a>
      <button class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" id="submit" type="submit">
        <?php echo \StoreCore\I18N\COMMAND_SAVE; ?>
      </button>
    </div>
    <div class="mdl-card__menu">
      <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
        <i class="material-icons">help</i>
      </button>
    </div>
  </div>
</form>
